### ISSUE TITLE
How to fetch this repo's code?

### ISSUE THREAD

**Issue by Moybot2000** [Smiley-Cartoons/Happy-Burgers#11]
hey andre could you update the code that i made at your house so i can use it i nee the code with the burger so i can work with the animation and health bar

thx

**Comment by AndreBacic** [comment]
(Assuming I'm answering your question and have not misunderstood you)
The code we worked on Thursday is in all three branches of this repo.
To download the current code, you can go to the main branch (or any other, I guess) and press the big green "Code" button and select Download Zip, and then extract all items from that zip folder so you can work with them.

To save your changes, you have basically two options:
1) Go to the moybot-changes branch (click on the drop-down menu button that probably says "main", which is to the far left of the green Code button, and select your branch) and add and commit the files you've created/changed.
2) Use an IDE or code editor (I recommend Visual Studio Code) and set up git and github controls to do option 1 for you. This option is a bit challenging to set up properly (requires some research), but saves you a lot of time and trouble in the long run.

**Comment by Moybot2000** [comment]
Thx 🙏

**Comment by AndreBacic** [comment]
Since this conversation as saved under closed issues, I will now close this issue.
