### ISSUE TITLE
No images to work with

### ISSUE THREAD

**Issue by AndreBacic** [Smiley-Cartoons/Happy-Burgers#2]
@Smiley-Cartoons please commit some images so we (especially @Moybot2000) have some images to start working with.

**Comment by Smiley-Cartoons** [comment]
Sorry I was late. I just added some images of the berger walking forward.

**Comment by AndreBacic** [comment]
Thanks for adding the images!
 ummm . . . . I don't believe you need to make twenty-two images for one animation. I don't know what your research has told you, but I've heard that people can't tell the subtle differences in those images. 

Just three images would work perfectly fine for a character with no knees: the 1st with parallel legs, the 2nd with the right leg forward and the 3rd with the left leg forward, and then the animation goes in a four image loop: 1, 2, 1, 3, 1, 2, 1, 3, etc. You could save yourself a lot of time and storage space by just doing three pictures per animation, and later we can add more if needed.

**Comment by AndreBacic** [comment]
@Smiley-Cartoons by the way, if the game is called 'Happy Burgers' shouldn't the burger be smiling? Also, are we calling them b**_u_**rgers or b**_e_**rgers?

**Comment by AndreBacic** [comment]
@Smiley-Cartoons by the way, if the game is called 'Happy Burgers' shouldn't the burger be smiling? Also, are we calling them b_u_rgers or b_e_rgers?

**Comment by AndreBacic** [comment]
@Smiley-Cartoons by the way, if the game is called 'Happy Burgers' shouldn't the burger be smiling? Also, are we calling them b**_u_rgers or b**_e_rgers?

**Comment by AndreBacic** [comment]
@Smiley-Cartoons by the way, if the game is called 'Happy Burgers' shouldn't the burger be smiling? Also, are we calling them b**u**rgers or b**e**rgers?

**Comment by Smiley-Cartoons** [comment]
Ok I just took out the old images and added new ones. If you could add those to a folder that'd be great. You (Andre) can be the organizer because I don't know exactly where y'all want the files.

**Comment by Smiley-Cartoons** [comment]
And yes that was a misspelling. We should call them burgers

**Comment by Smiley-Cartoons** [comment]
Oh and about them smiling. I don't think we'll call it happy burgers. And the story line will probably include them being mad/sad. So we'll have to think of a better name at some point

**Comment by AndreBacic** [comment]
Ok so "Angry Burgers"?

I thought it would be best to put all of the images in an images folder, with each animation set grouped into its own folder, so I'll keep doing that if you don't mind.

btw you can use the @ symbol to reference specific people

**Comment by Smiley-Cartoons** [comment]
That could work. Although it sounds a bit too much like angry birds. We can keep thinking tho.

**Comment by Smiley-Cartoons** [comment]
Yeah that sounds good! Ok cool!

**Comment by Smiley-Cartoons** [comment]
@Moybot2000 the images for the burgers are in the repository so you can get working whenever (incase I didn't already say that). And the tower image will probably come tomorrow.
