### ISSUE TITLE
No repo description

### ISSUE THREAD

**Issue by AndreBacic** [Smiley-Cartoons/Happy-Burgers#8]
We have a readme file, but no description. I believe only @Smiley-Cartoons can add a description, so if you would put something professional and descriptive there that would be helpful. Thank you!

**Comment by Smiley-Cartoons** [comment]
So did you add that description?

**Comment by AndreBacic** [comment]
No, because it won't let me. 
If you click the <>Code tab, to the right is a section named 'About,' which states that no description has been provided. I believe only you can add a description, and it would be beneficial if you did.

**Comment by AndreBacic** [comment]
Thank you!
